### PR TITLE
Enforce max log files limit properly

### LINKED ISSUE #10230: [QA] Too many log files kept
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Too many log files are kept

### Steps to reproduce the issue

1. Go to Settings -> Log Settings  
2. Set 'Log files to keep' to 5
3. Make sure 6 log files get created (e.g. restart the client 6 times) 

### Screenshots

Screenshot 2022-11-02 at 16 54 32

### Expected behavior

5 files are kept in the log folder

### Actual behavior

6 files are kept in the log folder

### PR DESCRIPTION
**Pull request by fmoc**
Fixes #10230.

### CODE REVIEW

File: src/libsync/logger.cpp [hunk 1]
```diff
@@ -325,6 +313,21 @@ void Logger::rotateLog()
...
+            {
+                auto oldLogFiles = dir.entryList(QStringList(QStringLiteral("*%1-*.log.gz").arg(qApp->applicationName())), QDir::Files, QDir::Name);
+
+                // keeping the last maxLogFiles files in total (need to subtract one from maxLogFiles to ensure the limit)
+                std::sort(oldLogFiles.begin(), oldLogFiles.end(), std::greater<QString>());
+                oldLogFiles.erase(oldLogFiles.begin(), oldLogFiles.begin() + std::min(maxLogFiles - 1, oldLogFiles.size()));
+
+                for (const auto &s : oldLogFiles) {
+                    if (!QFile::remove(dir.absoluteFilePath(s))) {
+                        qCWarning(lcUtility) << "Failed to remove old log file" << s;
```
Comment (TheOneRing) [inline src/libsync/logger.cpp:327]: While we are in a runnable, calling the logger from the logger can cause issues.

Comment (fmoc) [reply src/libsync/logger.cpp:327]: I see. I'll switch back to the original solution.
