### PR TITLE
Properly display directory size in selective sync widget

### LINKED ISSUE #11255: [QA] [gui-tests] Squish test hardfailure while sorting folders
### Describe the QA issue

GUI test fails while sorting folder list by size.

Example CI builds:
https://drone.owncloud.com/owncloud/client/16696/2/15
https://drone.owncloud.com/owncloud/client/16699/3/15
https://drone.owncloud.com/owncloud/client/16700/3/15
https://drone.owncloud.com/owncloud/client/16701/3/15
https://drone.owncloud.com/owncloud/client/16702/3/15
https://drone.owncloud.com/owncloud/client/16703/3/15

### Screenshots

Screenshot from 2023-10-02 09-56-37

### PR DESCRIPTION
**Pull request by fmoc**
Fixes a regression introduced in #11237.

Fixes #11255.

### CODE REVIEW

File: src/common/utility.cpp [hunk 1]
```diff
@@ -463,6 +463,18 @@ void Utility::sortFilenames(QStringList &fileNames)
     std::sort(fileNames.begin(), fileNames.end(), collator);
 }
 
+QString Utility::concatUrlPathItems(std::initializer_list<QString> items, const QLatin1Char delimiter)
```
Comment (TheOneRing) [inline src/common/utility.cpp:466]: QStringView

File: src/common/utility.cpp [hunk 2]
```diff
@@ -463,6 +463,18 @@ void Utility::sortFilenames(QStringList &fileNames)
...
+{
+    QStringList result;
+    for (QString item : items) {
+        while (item.endsWith(QLatin1Char('/'))) {
+            item = item.left(item.size() - 1);
```
Comment (TheOneRing) [inline src/common/utility.cpp:471]: No need to copy, you can remove the trailing slash in the QStringView

File: src/common/utility.cpp [hunk 3]
```diff
@@ -463,6 +463,18 @@ void Utility::sortFilenames(QStringList &fileNames)
     std::sort(fileNames.begin(), fileNames.end(), collator);
 }
 
+QString Utility::concatUrlPathItems(std::initializer_list<QString> items, const QLatin1Char delimiter)
+{
+    QStringList result;
```
Comment (TheOneRing) [inline src/common/utility.cpp:468]: reserve items.size()

File: src/gui/selectivesyncwidget.cpp [hunk 4]
```diff
@@ -115,6 +115,9 @@ void SelectiveSyncWidget::refreshFolders()
 void SelectiveSyncWidget::setFolderInfo(const QString &folderPath, const QString &rootName, const QSet<QString> &oldBlackList)
 {
     _folderPath = folderPath;
+    if (_folderPath.endsWith(QLatin1Char('/'))) {
+        _folderPath.remove(_folderPath.size() - 1, 1);
```
Comment (TheOneRing) [inline src/gui/selectivesyncwidget.cpp:119]: chop

**Review by TheOneRing — DISMISSED** [review]

**Review by TheOneRing — APPROVED** [review]
