### PR TITLE
Fix OpenID Connect authentication regression

### LINKED ISSUE #9324: [2.10.0] Can not connect to oCIS
With the client version 2.10.0 rc2 and also 2.11.0-git it is not possible to connect a new account to oCIS. The same setup works with client version 2.9.2.

The client opens the browser with this URL:
```
http://127.0.0.1:35619/?code=QuOxd7Kn10pIf9oEPsY5S0rXXXn-hgrC&scope=profile%20openid%20offline_access%20email&session_state=4bXXXXb7373c63a1e95a07bc7949e0afd5d80d0ea637c761dde60546e5b5baf3.yvhihIZJcp02lGGL0IX1PB-oVi3VsHUO9ltxpVYUkp8%3D&state=QBxRZrrE8SSSUPbie5VImhCR-Y4agUbCY8_n-NFRJcQ%3D
```
and after allowing access the browser reports
grafik

The OIDC redirect url seems empty.

### PR DESCRIPTION
**Pull request by fmoc**
Introduced in ba37025f4b5ac4a2a6cde6aac7d4a5896cfbac1.

Closes #9324.

### CODE REVIEW

File: src/libsync/creds/oauth.cpp [hunk 1]
```diff
@@ -224,16 +224,22 @@ void OAuth::startAuthentication()
...
                     return;
                 }
+
+                // server port cannot be queried any more after server has been closed, which we want to do as early as possible in the processing chain
+                // therefore we have to store it beforehand
+                const auto serverPort = _server.serverPort();
+
                 // we only allow one response
-                qCDebug(lcOauth) << "Recieved the first valid request, stoping to listen";
+                qCDebug(lcOauth) << "Received the first valid response, closing server socket";
```
Comment (TheOneRing) [inline src/libsync/creds/oauth.cpp:233]: Actually we received a GET request as a response :P so wording is complicated here.

**Review by TheOneRing — APPROVED** [review]
