### PR TITLE
Always disable VFS when experimental features are disabled

### LINKED ISSUE #9781: [QA] 3.0.0 master branded client enables Linux experimental virtual files
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

It is possible to enable experimental Linux virtual files with 3.0.0 branded Linux client.
If 'forceVirtualFilesOption' is set, the client (here BtR client) enables VFS per default for a new account.

### Expected behavior

For branded Linux clients (except 'testpilotcloud') it should not be possible to enable the experimental VFS support. 

### Steps to reproduce the issue

_No response_

### Screenshots

BtR-VFS

### Logs

_No response_

### Client version number

3.0.0 master from git 08.06.2022

### Desktop environment (Linux only)

openSUSE 15.3

### Client package version and origin (Linux only)

_No response_

### Installation path (Windows only)

_No response_

### Server information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fmoc**
Fixes #9781.

### CODE REVIEW

File: src/gui/newwizard/pages/accountconfiguredwizardpage.cpp [hunk 1]
```diff
@@ -37,7 +37,7 @@ AccountConfiguredWizardPage::AccountConfiguredWizardPage(const QString &defaultS
         _ui->advancedConfigGroupBox->setVisible(false);
     }
 
-    if (!Theme::instance()->showVirtualFilesOption()) {
+    if (!Theme::instance()->enableExperimentalFeatures() || !Theme::instance()->showVirtualFilesOption()) {
```
Comment (TheOneRing) [inline src/gui/newwizard/pages/accountconfiguredwizardpage.cpp:40]: Only suffix vfs is considert experimental see `vfsModeIsExperimental`.

Comment (dragotin) [inline src/gui/newwizard/pages/accountconfiguredwizardpage.cpp:40]: Tbh, the `enableExperimentalFeatures()` should be moved into the `showVirtualFilesOption()`. Otherwise there are again two places where that is implemented, and the `showVirtualFilesOption` is exactly what it is about, or?

**Review by dragotin — CHANGES_REQUESTED** [review]

File: src/gui/newwizard/pages/accountconfiguredwizardpage.cpp (hunk 1 above)
Comment (fmoc) [reply src/gui/newwizard/pages/accountconfiguredwizardpage.cpp]: This is the case already. Currently, however, `forceVirtualFilesOption` is evaluated later than `showVirtualFilesOption`. "force" seems higher prio than "show". We can change this, though.
