### PR TITLE
Tell user which basic auth account they need to log in to

### LINKED ISSUE #11014: Show account name in "Login required" dialog
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When opening the sync client without unlocking the keyring with the passwords on Linux, the "Login required" dialog pops up.
In my case, I've got two accounts with the same username, but on different servers. So I get the exact same password prompt twice, but it doesn't show which prompt is for which server so I can't know.

### Expected behavior

I expected to see the corresponding account for the username and password.

### Steps to reproduce the issue

1. Start Owncloud sync client with multiple accounts
2. Do **not** unlock system keyring

### Screenshots

Screenshot_20230706_162412

### Logs

_No response_

### Client version number

ownCloud 4.1.0 [GITDIR](https://github.com/owncloud/client/commit/GITDIR-NOTFOUND)
Libraries Qt 5.15.10, OpenSSL 3.1.1 30 May 2023
Using virtual files plugin: suffix
opensuse-tumbleweed-6.3.9-1-default

### Desktop environment (Linux only)

OpenSUSE Tumbleweed 20230705
KDE Plasma 5.27.6
KDE Frameworks 5.107.0
Graphics Platform: X11

### Client package version and origin (Linux only)

Installed from standard openSUSE repository

### Installation path (Windows only)

_No response_

### Server information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fmoc**
Fixes #11014.

### CODE REVIEW

**Review by erikjv — APPROVED** [review]

File: src/gui/creds/httpcredentialsgui.cpp [hunk 1]
```diff
@@ -114,7 +114,7 @@ void HttpCredentialsGui::showDialog()
     // make sure it's cleaned up since it's not owned by the account settings (also prevents memory leaks)
     dialog->setAttribute(Qt::WA_DeleteOnClose);
 
-    dialog->setTopLabelText(tr("Please enter your password to log in to your account."));
+    dialog->setTopLabelText(tr("Please enter your password to log in to your account %1.").arg(_account->displayName()));
```
Comment (fmoc) [inline src/gui/creds/httpcredentialsgui.cpp:117]:
```suggestion
    dialog->setTopLabelText(tr("Please enter your password to log in to the account %1.").arg(_account->displayName()));
```

**Review by TheOneRing — APPROVED** [review]
