### PR TITLE
Fix custom user ID and hint handling

### LINKED ISSUE #10440: [QA] Display User ID Type in Wizard
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Selected User ID Type in ownBrander is not taken into account in Wizard
Client 3.1.0

### Steps to reproduce the issue

1. Set User ID Type in ownBrader to Email
2. Trigger the build
3. Add a server url into the new client

### Screenshots

Screenshot 2023-01-31 at 13 41 32

### Expected behavior

When User ID Type is **email**, the message is just 'Please enter your email address' and a blank field (might be with a hint).

When User ID Type is **username**, the message is just 'Please enter your username' and a blank field (might be with a hint).

When User ID Type is **custom**, the message is just 'Please enter your _Custom User ID_' and a blank field (might be with a hint), where _Custom User ID_ is a string from Custom User ID field in ownBrander.

### Actual behavior

The user is prompted to enter their username into the email address field

### PR DESCRIPTION
**Pull request by fmoc**
image

screenshot_2023-02-07_15-49-47

Fixes #10440.

Do we need changelog entries for these changes?

### CODE REVIEW

File: src/gui/loginrequireddialog/basicloginwidget.cpp [hunk 1]
```diff
@@ -30,14 +30,20 @@ BasicLoginWidget::BasicLoginWidget(QWidget *parent)
...
+            return Theme::instance()->customUserID();
+        default:
+            return Utility::enumToDisplayName(Theme::instance()->userIDType());
+        }
+    }();
+
     _ui->usernameLabel->setText(usernameLabelText);
     _ui->usernameLineEdit->setPlaceholderText(usernameLabelText);
 
-    if (!Theme::instance()->userIDHint().isEmpty()) {
```
Comment (TheOneRing) [inline src/gui/loginrequireddialog/basicloginwidget.cpp:37]: Why was this removed

**Review by TheOneRing — CHANGES_REQUESTED** [review]

**Review by TheOneRing — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14221/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14221/oc10/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14221/oc10/guiReportUpload/serverlog.log

Screenshots:
- [Delete_a_folder.png](https://cache.owncloud.com/public/owncloud/client/14221/oc10/guiReportUpload/screenshots/Delete_a_folder.png)

</details>

**Comment by HanaGemela** [comment]
Still broken in qa 4.0.0.10487-alpha1

**Comment by HanaGemela** [comment]
Passed in qa 4.0.0.10497-alpha1, mac
