### PR TITLE
SelectiveSync: Verify if the list could be read from journal.

### LINKED ISSUE #4633: Selective Sync: Handle DB Read Error
### Expected behaviour

If database access fails for whatever reason while reading the selective sync information and reading of the info fails, we should bail out with an critical error.

### Current behaviour

If the select fails, it looks to the user as if the selective sync information is just lost.

### PR DESCRIPTION
**Pull request by dragotin**
If there is a read error from the database while trying to get
the list from database, make sure to not behave badly because
the list is empty.

Supposed to fix #4633

### CODE REVIEW

File: src/gui/selectivesyncdialog.cpp [hunk 1]
```diff
@@ -391,12 +391,17 @@ qint64 SelectiveSyncTreeView::estimatedSize(QTreeWidgetItem* root)
...
+    bool ok;
     init(account, tr("Unchecked folders will be <b>removed</b> from your local file system and will not be synchronized to this computer anymore"));
-    _treeView->setFolderInfo(_folder->remotePath(), _folder->alias(),
-                             _folder->journalDb()->getSelectiveSyncList(SyncJournalDb::SelectiveSyncBlackList));
-
+    QStringList selectiveSyncList = _folder->journalDb()->getSelectiveSyncList(SyncJournalDb::SelectiveSyncBlackList, &ok);
+    if( ok ) {
+        _treeView->setFolderInfo(_folder->remotePath(), _folder->alias(),selectiveSyncList);
+    } else {
+        _okButton->setEnabled(false);
```
Comment (ogoffart) [inline src/gui/selectivesyncdialog.cpp]: i must be missing something but i think _okButton is allaws null here.

Comment (ogoffart) [inline src/gui/selectivesyncdialog.cpp]: ah yes, i missed the call to init()

File: src/libsync/syncengine.cpp [hunk 2]
```diff
@@ -762,7 +766,13 @@ void SyncEngine::startSync()
     DiscoveryJob *discoveryJob = new DiscoveryJob(_csync_ctx);
     discoveryJob->_selectiveSyncBlackList = selectiveSyncBlackList;
     discoveryJob->_selectiveSyncWhiteList =
-        _journal->getSelectiveSyncList(SyncJournalDb::SelectiveSyncWhiteList);
+        _journal->getSelectiveSyncList(SyncJournalDb::SelectiveSyncWhiteList, &ok);
+    if (!ok) {
+        delete discoveryJob;
+        qDebug() << Q_FUNC_INFO << "Unable to read selective sync list, aborting.";
+        return;
```
Comment (ogoffart) [inline src/libsync/syncengine.cpp]:
```
        emit csyncError(tr("Unable to read from the sync journal."));
        finalize(false);
        return
```

File: src/libsync/syncengine.cpp [hunk 3]
```diff
@@ -733,10 +733,14 @@ void SyncEngine::startSync()
...
-    bool usingSelectiveSync = (!selectiveSyncBlackList.isEmpty());
-    qDebug() << (usingSelectiveSync ? "====Using Selective Sync" : "====NOT Using Selective Sync");
-
+    bool ok;
+    auto selectiveSyncBlackList = _journal->getSelectiveSyncList(SyncJournalDb::SelectiveSyncBlackList, &ok);
+    if (ok) {
+        bool usingSelectiveSync = (!selectiveSyncBlackList.isEmpty());
+        qDebug() << Q_FUNC_INFO << (usingSelectiveSync ? "====Using Selective Sync" : "====NOT Using Selective Sync");
+    } else {
+        qDebug() << Q_FUNC_INFO << "Could not retrieve selective sync list from DB";
```
Comment (ogoffart) [inline src/libsync/syncengine.cpp]: Then you don't want to continue the sync or it will sync everything !

```
        emit csyncError(tr("Unable to read the blacklist from the local database"));
        finalize(false);
        return;
```

**Comment by guruz** [comment]
> Supposed to fix #4633 

(Only if it verifies ALL DB reads..)

**Comment by dragotin** [comment]
Thanks @ogoffart, I pushed a fix for the stuff you mentioned.

**Comment by ogoffart** [comment]
:+1:
