### PR TITLE
Work/sparkle errors

### LINKED ISSUE #10531: Sparkle updater errors are not logged sufficiently
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

When using a self-hosted HTTP-only update server, the Sparkle updater reports an error:

image

One would assume that the updater now terminates, but it seems to continue:

image

So far, so good. Now, when we click `Install update`:

image

My guess is that since the URL provided by the updater is also HTTP and not HTTPS, the updater refuses to continue. Unfortunately, we can't tell for sure. The regular Sparkle updater log, `~/Library/Logs/SparkleUpdaterLog.log` is not being used by our own updater. This is likely due to the fact that we use the Objective-C API, which provides some handlers to handle errors manually. We do use some of these handlers, but this seems insufficient.

Long story short: we need better error logging for the Sparkle updater. Currently, it is impossible to tell for sure why the scenario described above failed.

### Proposed solution

Looking at Sparkle's [updater API docs](https://sparkle-project.org/documentation/api-reference/Protocols/SPUUpdaterDelegate.html), I noticed we only override a few of the handlers. I could imagine we need to override more of these (basically all of them which are passed an error). 

### Alternative solutions you considered

Maybe we can enable writing a log file to our config directory, or maybe there is a callback interface that can provide Sparkle's log messages to us. If possible, we should increase the verbosity of the update server.

### Additional context

I am going to deploy the config used to produce this bug on our demo update server later. I'll provide a URL then.

Another Sparkle issue (which is not really related, but could be worked on, too, while we're at it anyway): https://github.com/owncloud/client/issues/7592

### PR DESCRIPTION
**Pull request by erikjv**
Fixes #10531.

### CODE REVIEW

File: src/gui/updater/sparkleupdater_mac.mm [hunk 1]
```diff
@@ -59,7 +59,8 @@ - (void)updater:(SUUpdater *)updater willInstallUpdate:(SUAppcastItem *)update
 - (void) updater:(SUUpdater *)updater didAbortWithError:(NSError *)error
 {
     Q_UNUSED(updater)
-    qCDebug(OCC::lcUpdater) << error.description;
+    qCWarning(OCC::lcUpdater) << error.localizedDescription; // user facing error
+    qCInfo(OCC::lcUpdater) << "Full error description:" << error.description;
```
Comment (fmoc) [inline src/gui/updater/sparkleupdater_mac.mm:63]: `qCInfo` is user facing, too, isn't it?

**Review by fmoc — CHANGES_REQUESTED** [review]

File: src/gui/updater/sparkleupdater_mac.mm [hunk 2]
```diff
@@ -59,7 +59,8 @@ - (void)updater:(SUUpdater *)updater willInstallUpdate:(SUAppcastItem *)update
 - (void) updater:(SUUpdater *)updater didAbortWithError:(NSError *)error
 {
     Q_UNUSED(updater)
-    qCDebug(OCC::lcUpdater) << error.description;
+    qCWarning(OCC::lcUpdater) << error.localizedDescription; // user facing error
```
Comment (fmoc) [inline src/gui/updater/sparkleupdater_mac.mm:62]:
```suggestion
    qCWarning(OCC::lcUpdater) << error.localizedDescription;
```

**Review by fmoc — APPROVED** [review]
