### PR TITLE
Fix OAuth2 refresh

### LINKED ISSUE #9975: OIDC dynamic registation fails as we don't restore _dynamicRegistrationData from keychain
When we refreshAuthentication is called the _dynamicRegistrationData  was not fetched from the keychain.
This results in a new registration.
With the now new client id, the refresh token is invalid.

Tested with https://ocis.team.owncloud.works/
Requires https://github.com/owncloud/client/pull/9974

### PR DESCRIPTION
**Pull request by fmoc**
Moves the relevant code into our account-based subclass.

Fixes #9975.

### CODE REVIEW

File: src/libsync/creds/oauth.cpp [hunk 1]
```diff
@@ -636,4 +571,89 @@ void AccountBasedOAuth::fetchWellKnown()
...
+                return credentialsJob->data().value<QVariantMap>();
+            } else {
+                qCCritical(lcOauth) << "Failed to read client id" << credentialsJob->errorString();
+                return {};
+            }
+        }();
+
+        _dynamicRegistrationData = data;
+
+        doRefresh();
```
Comment (TheOneRing) [inline src/libsync/creds/oauth.cpp:655]: Does using the lambda doRefresh actually solve a problem?

I'm kind of getting the impression that one linear spaghetti style function here would be easier to parse than what we  got here with  doRefresh and the parse lambda.

Comment (fmoc) [reply src/libsync/creds/oauth.cpp:655]: I tried to keep the original function encapsulated. It's already way too complex. But I also don't mind refactoring this, if you wish.

File: src/libsync/creds/oauth.cpp [hunk 2]
```diff
@@ -636,4 +571,89 @@ void AccountBasedOAuth::fetchWellKnown()
...
+            } else {
+                refresh();
+            }
+        });
+        fetchWellKnown();
+    };
+
+    auto credentialsJob = _account->credentialManager()->get(dynamicRegistrationDataC());
+
+    connect(credentialsJob, &CredentialJob::finished, this, [=] {
```
Comment (TheOneRing) [inline src/libsync/creds/oauth.cpp:641]: We got  100% duplication with startAuthentication, please refactor

**Review by TheOneRing — APPROVED** [review]
Looks good
