### PR TITLE
fix #5015 overlay icon not show: compare folder paths with no case-se…

### LINKED ISSUE #5015: [Overlay][Windows8/7][Testpilot] Overlay icons are not shown
### Expected behaviour
Overlay icons should appear on Shared sync folder

### Actual behaviour
Overlay icons are not show

### Steps to reproduce
1. Fresh install with [testpilotcloud-2.2.3.6210-nightly20160628-setup.exe](https://download.owncloud.com/desktop/daily/testpilotcloud-2.2.3.6210-nightly20160628-setup.exe)
2. Restart computer
3. Open Shared Syn folder

### Server configuration
ServerOS: Ubuntu 14.04 LTE
ServerVersion: 9.1.0 beta 2
### Client configuration

ClientOS: W7/W8.1
ClientVersion:  Version 2.2.3-nightly20160628 (build 6210)

Extra info:

 - Restart computer does not help this time
 - Regedit shows proper entries
 - ShExtView does not show anything abnormal
 - Date associated to shellext files 6/9/2016 6:31 PM (Seems to be the same files that official 2.2.2 client uses)

### PR DESCRIPTION
**Pull request by ArthurChiao**
fix #5015 overlay icon not shown

### CODE REVIEW

File: src/gui/folderman.cpp [hunk 1]
```diff
@@ -849,7 +849,7 @@ Folder *FolderMan::folderForPath(const QString &path)
     foreach(Folder* folder, this->map().values()) {
         const QString folderPath = folder->cleanPath()+QLatin1Char('/');
 
-        if(absolutePath.startsWith(folderPath)) {
+        if(absolutePath.startsWith(folderPath, Qt::CaseInsensitive)) {
```
Comment (dragotin) [inline src/gui/folderman.cpp]: I think this should rather be 
```
startsWith(folderPath, Utility::isLinux() || Utility::isBSD() ? Qt::CaseSensitive : Qt::CaseInsensitive)) {
..
```
because in case of case sensitive file system, we want to compare case sensitive.

**Comment by dragotin** [comment]
@ArthurChiao great catches, thanks for your work!

@jturcotte what do you think?

File: src/gui/folderman.cpp (hunk 1 above)
Comment (ArthurChiao) [inline src/gui/folderman.cpp]: great, i only tested windows platform.

Comment (jturcotte) [inline src/gui/folderman.cpp]: Utility::isMac() should also generally be casesensitive, so maybe `Utility::isWindows() ? Qt::CaseInsensitive : Qt::CaseSensitive`?

File: shell_integration/windows/OCOverlays/OCOverlay.cpp [hunk 2]
```diff
@@ -110,17 +110,17 @@ IFACEMETHODIMP OCOverlay::GetPriority(int *pPriority)
...
+		*pPriority = 2; break;
 	case State_Sync:
-		*pPriority = 3;
+		*pPriority = 3; break;
 	case State_Error:
-		*pPriority = 4;
+		*pPriority = 4; break;
 	default:
-		*pPriority = 5;
+		*pPriority = 5; break;
```
Comment (jturcotte) [inline shell_integration/windows/OCOverlays/OCOverlay.cpp]: Oh... those were missing for real?

Comment (ArthurChiao) [inline shell_integration/windows/OCOverlays/OCOverlay.cpp]: they are missing in current code, both on branch `2.2` and `master` (although client also works on missing them)

File: src/gui/folderman.cpp (hunk 1 above)
Comment (dragotin) [inline src/gui/folderman.cpp]: I doubt that Mac is case sensitive. It is case **preserving**, but */Users/kf/Buds/Spencer* is the same file as */Users/kf/buds/Spencer*, right?

Comment (jturcotte) [inline src/gui/folderman.cpp]: The file system has the case-sensitive option when you format, but you're right, the default is incensitive while I thought that it was sensitive 😮
So please ignore my request.

**Comment by guruz** [comment]
@ArthurChiao Hi! have you seen the comment above https://github.com/owncloud/client/pull/5025#issuecomment-229863194 ?

**Comment by ArthurChiao** [comment]
@guruz hi，i've seen the comments, should i change the code to

 ```cpp
startsWith(folderPath, Utility::isWindows() ? Qt::CaseInsensitive : Qt::CaseSensitive))
```
? 

I'm not sure whether there are platforms which ownCloud supports that cares about case-sensitivity in file paths.

**Comment by guruz** [comment]
@ArthurChiao I meant the other comment about the contributor agreement:)

**Comment by dragotin** [comment]
As I discussed with @jturcotte before: I believe we need to be case insensitive on MacOSX as well. That one is only case preserving.

**Comment by ArthurChiao** [comment]
@dragotin thanks, update code again!

**Comment by DeepDiver1975** [comment]
> @guruz i've signed the agreement and sent it to cla@owncloud.com. Thanks :)

received - THX - you have been added to the team.

Welcome to the show! :tada:

**Comment by ArthurChiao** [comment]
@DeepDiver1975 nice :)

**Comment by guruz** [comment]
@danimo @jturcotte we'd need an update of the DLL binaries. Thanks.
