### PR TITLE
Fix encoding of Gtk bookmarks

### LINKED ISSUE #10280: Escape Gtk 3.0 bookmarks correctly
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Currently, our Gtk 3.0 bookmark generation does not escape new entries correctly. This causes a variety of issues, as documented in #9752. On MATE, this even prevents the entries from being displayed at all.

### Expected behavior

We should URL-escape the entries we add.

### Steps to reproduce the issue

Run any of the distros mentioned in #9752.

### Screenshots

_No response_

### Logs

_No response_

### Client version number

3.0.0-beta1/2 or any recent daily.

### Desktop environment (Linux only)

_No response_

### Client package version and origin (Linux only)

_No response_

### Installation path (Windows only)

_No response_

### Server information

_No response_

### Additional context

Follow-up from #9752.

### PR DESCRIPTION
**Pull request by fmoc**
This should fix #10280. I could not find any other encoding issues other than spaces while testing on a variety of distributions an desktops. 

Unfortunately, there is little to no documentation on how this file should really be structured. We have not seen any issues other than with spaces in paths so far, though. We can add additional escaping in the future if needed.

### CODE REVIEW

File: src/common/utility_unix.cpp [hunk 1]
```diff
@@ -32,7 +32,7 @@ void Utility::setupFavLink(const QString &folder)
 {
     // Nautilus: add to ~/.gtk-bookmarks
     QFile gtkBookmarks(QDir::homePath() + QLatin1String("/.config/gtk-3.0/bookmarks"));
-    QByteArray folderUrl = QUrl::fromLocalFile(folder).url(QUrl::ComponentFormattingOption::EncodeSpaces).toUtf8();
+    QByteArray folderUrl = QUrl::fromLocalFile(folder).toEncoded(QUrl::ComponentFormattingOption::EncodeSpaces);
```
Comment (TheOneRing) [inline src/common/utility_unix.cpp:35]: const?

**Review by TheOneRing — APPROVED** [review]
